spring.application.name=salonflow
# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=salon-images
# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

#JWT
jwt.secret=MyVeryStrongSecretKeyForSalonFlowProjectJWT2026SecurityKey
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
jwt.reset-password-expiration=1800000

# EMAIL (RESEND)
mail.provider=resend
resend.api-key=re_im6xDQ66_915jPz7z3r6k4EQY4dv28DKv
resend.from=onboarding@resend.dev

server.port=9090
frontend.url=http://localhost:5173
